[package]
name = "my_program"
version = "0.1.0"
edition = "2021"
default-run = "my_program"

[[bin]]
name = "create_file"
path = "src/create_file.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
